### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by pravdomil**
added:
torch
torchvision

### CODE REVIEW

**Comment by MackinationsAi** [comment]
Any particular reason for the addition, this is already in the one_click_install.bat -```pip install torch==2.3.0+cu121 torchvision==0.18.0+cu121 xformers==0.0.26.post1 --index-url https://download.pytorch.org/whl/cu121 --no-cache-dir```?

**Comment by pravdomil** [comment]
I'm doing the usual `pip install -r requirements.txt` on macOS

**Comment by MackinationsAi** [comment]
In that case, sounds like I should add a requirements_macos.txt file w/ that added dependencies for MacOS users (plus update the one_click_install.sh), bc if torch & torchvision are added to the requirements.txt file it will overwrite the versions I mentioned above for windows users during the installation causing issues.

**Comment by pravdomil** [comment]
https://stackoverflow.com/questions/29222269/is-there-a-way-to-have-a-conditional-requirements-txt-file-for-my-python-applica

something like this should work:
`atomac==1.1.0; sys_platform == 'darwin'`

**Comment by MackinationsAi** [comment]
Just made a requirements_macos.txt file, so ```pip install -r requirements_macos.txt``` on macOS is good to go.

**Pull request closed without merging**
